jobs:
  include:
    - stage: running lint and tests
      sudo: false
      language: node_js
      env:
        - APP_DIR=src
      node_js:
        - 8
        - 10
        - 12
        - node
      script:
        - npm install
        - npm run lint
        - npm test
    - stage: deploy
      before_deploy: 'npm run prepublishOnly'
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        on:
          branch: master
        skip_cleanup: true
        edge: true
notifications:
  email:
    on_success: never
    on_failure: always
